### ISSUE TITLE
403 Forbidden SignatureDoesNotMatch

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/website#167] opened 2023-12-24 15:02 UTC
https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0+snapshot-english.tar.xz

403 Forbidden
Code: SignatureDoesNotMatch
RequestId: tx00000b7f2c70ee80d0135-00658847d4-2bc58ec-prg
HostId: 2bc58ec-prg-eu-1

**Comment by celestinoxp** [comment] 2024-01-15 16:23
i found a way to download, the problem seems to be + signal in the link, so only we beed to change to a codified way, we can change "+" by "%2B"
In my case i want do download 5.2, i use:
https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2%2Bsnapshot-all-languages.zip

**Comment by williamdes** [comment] 2024-03-19 14:27
Let's follow in #164

**Comment by williamdes** [comment] 2024-03-19 14:27
Duplicate of #164

**Closed by williamdes** 2024-03-19 14:27 UTC
